let data,result;
data = new Date();
// result = data. getFullYear();
// data.getMonth();
 data.getDate();
// data.getDay();
// data.getHours();
// data.getMinutes(); 
// data.getSeconds();
// data.getMilliseconds();
// data.getTime();
// data.getTimezoneOffset();
console.log(data);